import {
  ADD_COMIC,
  ADD_COMIC_FAIL,
  ADD_COMIC_SUCCESS,
  DELETE_COMIC,
  DELETE_COMIC_FAIL,
  DELETE_COMIC_SUCCESS,
  GET_COMIC,
  GET_COMIC_FAIL,
  GET_COMIC_SUCCESS,
  GET_LAST_COMIC,
  GET_LAST_COMIC_FAIL,
  GET_LAST_COMIC_SUCCESS,
} from './actionsConstants';

export {
  ADD_COMIC,
  ADD_COMIC_FAIL,
  ADD_COMIC_SUCCESS,
  DELETE_COMIC,
  DELETE_COMIC_FAIL,
  DELETE_COMIC_SUCCESS,
  GET_COMIC,
  GET_COMIC_FAIL,
  GET_COMIC_SUCCESS,
  GET_LAST_COMIC,
  GET_LAST_COMIC_FAIL,
  GET_LAST_COMIC_SUCCESS,
};
